### PR TITLE
RC4 in C, for better memory performance

### PR DESCRIPTION
**Pull request by PeterDWhite**
Using FFI bindings

### CODE REVIEW

**Comment by vincenthz** [comment]
That's a not a bad idea to have a C implementation, however i'ld like to see if an impure haskell implementation can just be enough for memory usage and performance.

Regarding this implementation, it has many problems:

The first problem is the Makefile, you need to have the simple mechanism, that aes use, to build rc4.
Code wise, this need type cleanup (using standard uintX_t types), removal of hsc2hs, move all allocation on the haskell side.

**Comment by PeterDWhite** [comment]
Hi Vincent:

We have an impure Haskell implementation, which I modified to make more readable. Its performance is comparable to the C version. However, it uses some GHC specific imports, namely GHC.ForeignPtr, GHC.Exts, and GHC.ST. I also have versions without these imports, but so far they always suffer in performance.

I will change the C types to uintX_t types.

On allocation, I am finding that doing a malloc of the output buffer in C, and then using an opaque type to reference the output buffer, is working out OK, The memory appears to get cleaned up later. But I want to try moving it to Haskell, this might remove some of the spikiness I have observed in the memory usage.

For removing hsc2hs, I guess I can do that. I want to keep the same interface as the current RC4 implementation, passing a context in and out, where the caller does not really need to know the type of the context. To remove hsd2hs, I can bust the context into its three components and pass them into C, and then assemble the pieces again after C is done.

**Comment by PeterDWhite** [comment]
Should I make another branch with the low level Haskell implementation? Or another fork?

**Comment by PeterDWhite** [comment]
Completed the changes, except for getting rid of the Makefile.

**Comment by PeterDWhite** [comment]
OK, all the comments are addressed

**Comment by vincenthz** [comment]
Peter, i've started merging things yesterday. I shall push it to the master repository soon.

**Comment by pheaver** [comment]
Hi @vincenthz, is the code in a state that's acceptable now? Is there anything blocking it from getting released?

**Comment by vincenthz** [comment]
i've been splitting up cryptocipher, hence it took so long to release this up. This is now available in cipher-rc4 (0.1.1 latest). I'll update tls shortly to use cipher-rc4, and cryptocipher will use the new package in the next major version.

**Pull request closed without merging**
