### PR TITLE
Fix order in DES_EEE3 and DES_EDE3

### PR DESCRIPTION
**Pull request by stbuehler**

### CODE REVIEW

**Comment by vincenthz** [comment]
this is all rather arbitrary, got any KATs for 3DES maybe ?

**Comment by stbuehler** [comment]
Well, fixing the order got my handshake with gnutls working (which already has been working with AES, and is written in a very generic way), so i'm pretty sure the order is correct.

Also the docs I found (http://en.wikipedia.org/wiki/Triple_DES) suggest that you first apply E_k1, then D_k2, then E_k3 (and the keys k1, k2, k3 are obviously stored in that order to form the 3DES key).

I think this is just a typo as someone got confused about the order the functions are applied - `f . g . h` first applies h, then g, then f.

As you are writing a SSL/TLS implementation on your own just give it a try :)

Maybe you want to copy http://git.lysator.liu.se/nettle/nettle/blobs/master/testsuite/des3-test.c - but no idea where that test case is coming from (nettle is the backend used by gnutls).
I'm also working on a nettle binding for haskell, implementing your Crypto.Cipher.Types classes.

**Comment by vincenthz** [comment]
Alright, that seems sensible. it would be nice to have KATs instead of relying on other programs, but this is better than nothing.

That's great news for a nettle backend; This will make sure crypto-cipher-types is generic enough. One thing though is i've just started changing BlockCipher to be able to also do mutable/IO encryption, with something like:

```
ecbDecryptMutable :: cipher -> Ptr Word8 -> Ptr Word8 -> BufferLength -> IO ()
```

I'm not sure exactly how it's going to look on the final version, nor if the actual BlockCipher immutable class still make sense with the IO interface in place; My guess, is that they could all be defined from the mutable version and are likely to go much faster.

it's quite likely you would benefit from such a class sooner than later. what do you think ?

**Comment by stbuehler** [comment]
My own TLS project uses lazy bytestrings, and wasn't designed for performance (more a debug thing).
But I certainly could implement the mutable versions.

**Comment by vincenthz** [comment]
Thanks for the 3DES patch

**Pull request merged**
