### PR TITLE
Blowfish cipher

### PR DESCRIPTION
**Pull request by ghost**
Please add this quick-and-dirty port of Doug Hoyte's Blowfish implementation to cryptocipher.

I found this code in the package Crypto-4.2.4. There doesn't seem to be any other Blowfish implementation on Hackage, while Crypto is bitrotting and doesn't use crypto-api.

### CODE REVIEW

**Comment by TomMD** [comment]
The KATs for blowfish should probably be placed in crypto-api-tests for maximum community use.  Not to say this should have any impact on this pull request.

**Comment by ghost** [comment]
Good point, I'll look into forking that later.

**Comment by vincenthz** [comment]
thanks. this looks like some cool addition. i'll have a proper look and will pull when i get some free time.

**Comment by vincenthz** [comment]
Thanks. it's now part of cryptocipher. FYI, The best representation (used in the AES code) for tables is by using the MagicHash and overloadedStrings extensions to have the already packed data in the binary.

**Pull request merged**
